# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8000']
  -job_name:'node'
    static_configs:
    -targets:['192.168.101.30:9100']
